name: influsion_4_28
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  crypto: ^3.0.2
  sqflite: ^2.3.0
  dio: ^5.0.0
  path_provider: ^2.0.9
  file: ^7.0.0
  file_picker: ^4.6.1
  material_design_icons_flutter: ^7.0.7296
  fluttertoast: ^8.2.5
   # 波浪动画 https://pub-web.flutter-io.cn/packages/wave
  wave: ^0.2.2
  # 波浪动画测试
  # google_fonts: ^6.2.1
  # url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - img/background.png
    - img/login.png
    - img/icon/
    - img/nullData.png
